let x=5;
try{
    let y = x / a;
    console.log("value is " +y);
}catch(err){
    console.log("error occured "+err);
}